kind: pipeline
type: docker
name: default

steps:
  - name: "makepkg"
    image: archlinux:base-devel
    commands:
      - /drone/src/drone/build.sh

  - name: upload
    image: plugins/s3
    settings:
      bucket: ungoogled-chromium-builds
      source: /drone/src/*.zst
      target: ${DRONE_BUILD_NUMBER}
      strip_prefix: /drone/src/
      path_style: true
      endpoint: https://bucket.quinncasey.com
      access_key:
        from_secret: minio_access_key
      secret_key:
        from_secret: minio_secret_key
